export const data = [
    {
        key: '1',
        number: 1,
        itemCode: 'A001',
        productName: 'Laptop',
        manufacturingDate: '2023-01-15',
        rating: 4.5,
        review: 'Great product, very fast',
    },
    {
        key: '2',
        number: 2,
        itemCode: 'B002',
        productName: 'Smartphone',
        manufacturingDate: '2023-02-20',
        rating: 4.2,
        review: 'Good camera, battery life could be better',
    },
    {
        key: '3',
        number: 3,
        itemCode: 'C003',
        productName: 'Headphones',
        manufacturingDate: '2023-03-10',
        rating: 4.8,
        review: 'Excellent sound quality',
    },
    {
        key: '4',
        number: 4,
        itemCode: 'D004',
        productName: 'Smartwatch',
        manufacturingDate: '2023-04-05',
        rating: 3.9,
        review: 'Decent features, but battery drains quickly',
    },
    {
        key: '5',
        number: 5,
        itemCode: 'E005',
        productName: 'Tablet',
        manufacturingDate: '2023-05-12',
        rating: 4.1,
        review: 'Good for entertainment, could use more processing power',
    },
];